"""
Scraper configuration — add your PDF URLs or local file paths here.

Minimum required per entry:
  - source: "url" (download PDF) or "file" (local path)
  - url or path: the PDF location
  - short_name: short identifier for the act (e.g. "IA", "CPA")

Everything else is auto-generated by Ollama from the PDF:
  - act_number, effective_date, description → extracted by LLM
  - category → defaults to "general" if omitted

You can still provide any field manually to override the LLM:
  - act_number, category, effective_date, last_amended, description
"""

# ─── Request settings ───────────────────────────────────────────────
REQUEST_TIMEOUT = 60  # PDFs can be large
REQUEST_DELAY = 2.0
MAX_RETRIES = 3
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

# ─── LLM settings ──────────────────────────────────────────────────
OLLAMA_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "gemma3"  # or "gemma3:12b" for better quality
CHUNK_SIZE = 6000         # chars per LLM chunk (stay within context window)
CHUNK_OVERLAP = 500       # overlap between chunks to avoid splitting sections

# ─── Output ─────────────────────────────────────────────────────────
OUTPUT_DIR = "output"
PDF_CACHE_DIR = "pdf_cache"  # downloaded PDFs are cached here

# ─── South Africa ───────────────────────────────────────────────────
ZA_ACTS = [
    # MINIMAL — just provide the PDF; Ollama extracts everything else:
    # {
    #     "source": "file",
    #     "path": "./Insurance-Act-No--18-of-2017.pdf",
    #     "short_name": "IA",
    # },
    #
    # WITH URL — Ollama still extracts act_number, dates, description:
    # {
    #     "source": "url",
    #     "url": "https://www.gov.za/sites/default/files/gcis_document/201409/act68of2008.pdf",
    #     "short_name": "CPA",
    #     "category": "consumer",   # optional override
    # },
    #
    # FULLY SPECIFIED — skip LLM metadata extraction entirely:
    # {
    #     "source": "file",
    #     "path": "./pdfs/za/insurance_act_18_of_2017.pdf",
    #     "short_name": "IA",
    #     "act_number": "18 of 2017",
    #     "category": "insurance",
    #     "effective_date": "2018-07-01",
    #     "description": "Regulates the insurance industry in South Africa.",
    # },
]

# ─── United Kingdom ─────────────────────────────────────────────────
GB_ACTS = [
    # Minimal — Ollama extracts act_number, dates, description:
    # {
    #     "source": "url",
    #     "url": "https://www.legislation.gov.uk/ukpga/2015/15/data.pdf",
    #     "short_name": "CRA",
    # },
]

# ─── United States ──────────────────────────────────────────────────
US_ACTS = [
    # Minimal — Ollama extracts act_number, dates, description:
    # {
    #     "source": "url",
    #     "url": "https://www.govinfo.gov/content/pkg/PLAW-111publ203/pdf/PLAW-111publ203.pdf",
    #     "short_name": "TILA",
    # },
]

# ─── Australia ──────────────────────────────────────────────────────
AU_ACTS = [
    # Minimal — Ollama extracts act_number, dates, description:
    # {
    #     "source": "url",
    #     "url": "https://www.legislation.gov.au/C2004A00109/latest/download",
    #     "short_name": "CCA",
    # },
]

# ─── India ──────────────────────────────────────────────────────────
IN_ACTS = [
    # Minimal — Ollama extracts act_number, dates, description:
    # {
    #     "source": "file",
    #     "path": "./pdfs/in/insurance_act_1938.pdf",
    #     "short_name": "IA1938",
    # },
]

# ─── Registry ──────────────────────────────────────────────────────
COUNTRY_CONFIGS = {
    "ZA": ZA_ACTS,
    "GB": GB_ACTS,
    "US": US_ACTS,
    "AU": AU_ACTS,
    "IN": IN_ACTS,
}